swagger: "2.0"
info:
  title: "Trello GraphQL Backend API"
  description: "API Gateway for Task, Board, and User services"
  version: "1.0.0"
schemes:
  - https
paths:
  /task:
    options:
      summary: "CORS support for Task Service"
      operationId: "taskServiceOptions"
      responses:
        '204':
          description: "CORS preflight response"
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "*"
            Access-Control-Allow-Methods:
              type: string
              default: "GET, POST, OPTIONS"
            Access-Control-Allow-Headers:
              type: string
              default: "Content-Type, Authorization"
      x-google-backend:
        address: https://task-service-104926798924.us-central1.run.app
    post:
      summary: "Task Service"
      operationId: "taskService"
      x-google-backend:
        address: https://task-service-104926798924.us-central1.run.app
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: query
          schema:
            type: object
            properties:
              query:
                type: string
      responses:
        '200':
          description: "A successful GraphQL response from Task Service"
      security:
        - google_id_token: []  # Added Google SSO token-based security

  /board:
    options:
      summary: "CORS support for Board Service"
      operationId: "boardServiceOptions"
      responses:
        '204':
          description: "CORS preflight response"
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "*"
            Access-Control-Allow-Methods:
              type: string
              default: "GET, POST, OPTIONS"
            Access-Control-Allow-Headers:
              type: string
              default: "Content-Type, Authorization"
      x-google-backend:
        address: https://board-service-104926798924.us-central1.run.app
    post:
      summary: "Board Service"
      operationId: "boardService"
      x-google-backend:
        address: https://board-service-104926798924.us-central1.run.app
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: query
          schema:
            type: object
            properties:
              query:
                type: string
      responses:
        '200':
          description: "A successful GraphQL response from Board Service"
      security:
        - google_id_token: []  # Added Google SSO token-based security

  /user:
    options:
      summary: "CORS support for User Service"
      operationId: "userServiceOptions"
      responses:
        '204':
          description: "CORS preflight response"
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "*"
            Access-Control-Allow-Methods:
              type: string
              default: "GET, POST, OPTIONS"
            Access-Control-Allow-Headers:
              type: string
              default: "Content-Type, Authorization"
      x-google-backend:
        address: https://user-service-104926798924.us-central1.run.app
    post:
      summary: "User Service"
      operationId: "userService"
      x-google-backend:
        address: https://user-service-104926798924.us-central1.run.app
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: query
          schema:
            type: object
            properties:
              query:
                type: string
      responses:
        '200':
          description: "A successful GraphQL response from User Service"
      security:
        - google_id_token: []  # Added Google SSO token-based security

securityDefinitions:
  google_id_token:
    type: "oauth2"
    authorizationUrl: ""
    flow: "implicit"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: "104926798924-0m8a4e0l1elhus477miu6er0n8r1forf.apps.googleusercontent.com"  # Replace with your actual Google OAuth client ID
