name: CI/CD Pipeline for GraphQL APIs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud using a service account
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Configure Docker to use gcloud for authentication
      - name: Configure Docker to use gcloud for authentication
        run: |
          gcloud auth configure-docker --quiet

      # Step 5: Build and push Docker images for GraphQL APIs to GCR
      - name: Build and push user-service Docker image
        run: |
          docker build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service ./services/user-service
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service

      - name: Build and push task-service Docker image
        run: |
          docker build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/task-service ./services/task-service
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/task-service

      - name: Build and push board-service Docker image
        run: |
          docker build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/board-service ./services/board-service
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/board-service

      # Step 6: Deploy the APIs to Google Cloud Run
      - name: Deploy user-service to Cloud Run
        run: |
          gcloud run deploy user-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated

      - name: Deploy task-service to Cloud Run
        run: |
          gcloud run deploy task-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/task-service --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated

      - name: Deploy board-service to Cloud Run
        run: |
          gcloud run deploy board-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/board-service --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated

      # Step 7: Use a static OpenAPI spec file for API Gateway configuration
      - name: Deploy API Gateway with static OpenAPI spec
        run: |
          gcloud api-gateway api-configs create trello-backend-config \
              --api=trello-backend-api \
              --openapi-spec=api-gateway.yaml \
              --project=${{ secrets.GCP_PROJECT_ID }}

      # Step 8: Deploy API Gateway with the new configuration
      - name: Deploy API Gateway
        run: |
          gcloud api-gateway gateways update trello-backend-gateway \
              --api=trello-backend-api \
              --api-config=trello-backend-config \
              --location=${{ secrets.GCP_REGION }} \
              --project=${{ secrets.GCP_PROJECT_ID }}

      # Step 9: Run tests (optional)
      - name: Run API tests
        run: |
          curl -X POST https://<user-service-url> -d '{"query":"{ helloUser }"}'
          curl -X POST https://<task-service-url> -d '{"query":"{ helloTask }"}'
          curl -X POST https://<board-service-url> -d '{"query":"{ helloBoard }"}'
